dist: trusty

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

script:
   - mvn clean test

after_success:
  - mvn clean test jacoco:report coveralls:report
  - mvn clean test jacoco:report-aggregate coveralls:report
  - mvn clean test jacoco:report-aggregate 

# When any tests are present update script with:
#- mvn clean test jacoco:report coveralls:report
